#ifndef __UBITRACK_CONFIG_H_INCLUDED__
#define __UBITRACK_CONFIG_H_INCLUDED__
#define UBITRACK_COMPONENTS_PATH "${UBITRACK_COMPONENT_INSTALL_PATH}"
#define UBITRACK_COMPONENTS_RELAVIVEPATH "${UBITRACK_COMPONENT_INSTALL_DIRECTORY}"
#endif