include(CMakeFindDependencyMacro)
find_dependency(ubitrack_core)
find_dependency(ubitrack_vision)
find_dependency(ubitrack_dataflow)
find_dependency(OpenGL)
find_dependency(OpenCL)
include("${CMAKE_CURRENT_LIST_DIR}/utvisualizationTargets.cmake")