import glob

Import( '*' )

if not have_utvision or not have_utdataflow:
	print "utVision or utDataflow missing -- not building vision visualization"
	success = False
	Return('success')	
	
# create a common build environment for all drivers
utVisualizationEnv = masterEnv.Clone()

utVisualizationEnv.AppendUnique( **mergeOptions( utdataflow_all_options, utvision_all_options ) )
utVisualizationEnv.AppendUnique( LIBS = boost_libs( [ 'thread', 'system' ] ) )
utVisualizationEnv.Replace( no_import_lib = 1 )

Export( 'utVisualizationEnv' )

# glob all SConscript files in subdirectories
sconsfiles = globSourceFiles( "utVisualization/*/SConscript" )

# recurse into subdirectories and export driver build environment
SConscript( sconsfiles, [ 'utVisualizationEnv' ] )
success = True
Return('success')



